{
 "title": "Mac Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status!=\"200\"}[1m])",
     "legendFormat": "{{uri}}-{{status}}"
    }
   ]
  },
  {
   "title": "Avg response time by uri",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=\"/api/users\"}[1m])) by (uri)/sum(rate(http_server_requests_seconds_count{uri=\"/api/users\"}[1m])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{uri=\"/api/users\"}[1m])/rate(http_server_requests_seconds_count{uri=\"/api/users\"}[1m])",
     "legendFormat": "{{uri}}-{{status}}"
    }
   ]
  }
 ]
}